### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by yoshi-shimomichi** [yoshi-shimomichi/Home_Care_Community#28]
###概要
在宅介護をしている非介護従事者の
悩みや愚痴、体験などを共有・相談できるサービス

###実装予定の機能
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] パスワード変更機能
- [ ] 質問・つぶやき投稿機能
- [ ] コメント投稿機能
- [ ] お気に入り機能
- [ ] 検索機能
- [ ] 通知機能

###必要なページ
- [ ] トップ画面（投稿一覧画面）
- [ ] ユーザー新規登録画面
- [ ] ログイン画面
- [ ] パスワード再設定申請画面
- [ ] パスワード再設定申請メール送信画面
- [ ] パスワード再設定画面
- [ ] 新規投稿画面
- [ ] 投稿詳細画面
- [ ] 投稿編集画面
- [ ] コメント投稿画面
- [ ] コメント編集画面
- [ ] プロフィール詳細画面
- [ ] プロフィール編集画面
- [ ] 要介護者プロフィール詳細画面
- [ ] 要介護者プロフィール編集画面
- [ ] ユーザーの質問投稿一覧画面
- [ ] ユーザーのつぶやき一覧画面
- [ ] お気に入り投稿一覧画面
- [ ] 通知一覧画面
- [ ] 利用規約画面
- [ ] プライバシーポリシー画面

**Comment by takyyi** [comment]
こちら案内に沿って、GithubProjectとストーリーポイントも是非作成してみてください！

**Comment by yoshi-shimomichi** [comment]
<img width="1182" alt="スクリーンショット 2023-12-28 16 01 17" src="https://github.com/yoshi-shimomichi/Home_Care_Community/assets/133360582/d69c303f-58fc-4d66-8569-251ef078e541">

アプリ開発カリキュラムに沿って作成していたのですが、手順そのものが間違えているといった状態なのでしょうか。

**Comment by takyyi** [comment]
こちらからはそのプロジェクトは見えないので、見えるところに作成してください！

**Comment by yoshi-shimomichi** [comment]
「Projects」→「Link Projects」で上記画像のページに移動できると思いますので、
再度よろしくお願いします。

**Comment by takyyi** [comment]
LGTMです！
